In [1]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

Requirement already up-to-date: sklearn in /Applications/anaconda3/lib/python3.7/site-packages (0.0)
Requirement already satisfied, skipping upgrade: scikit-learn in /Applications/anaconda3/lib/python3.7/site-packages (from sklearn) (0.21.3)
Requirement already satisfied, skipping upgrade: scipy>=0.17.0 in /Applications/anaconda3/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.3.1)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /Applications/anaconda3/lib/python3.7/site-packages (from scikit-learn->sklearn) (0.13.2)
Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in /Applications/anaconda3/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.17.2)

In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

Requirement already satisfied: joblib in /Applications/anaconda3/lib/python3.7/site-packages (0.13.2)

In [1]:
import pandas as pd

# Read the CSV and Perform Basic Data Cleaning

In [2]:
df = pd.read_csv("exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

,koi_disposition,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,CONFIRMED,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,...,-81,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,FALSE POSITIVE,0,1,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,...,-176,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
2,FALSE POSITIVE,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,-174,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
3,CONFIRMED,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,...,-211,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
4,CONFIRMED,0,0,0,0,4.134435,1.050000e-05,-1.050000e-05,172.979370,0.001900,...,-232,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714

In [3]:
len(df)

6991

In [4]:
df['koi_disposition'].value_counts()

FALSE POSITIVE    3504
CONFIRMED         1800
CANDIDATE         1687
Name: koi_disposition, dtype: int64

In [37]:
columns = df.keys()
columns

Index(['koi_disposition', 'koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co',
       'koi_fpflag_ec', 'koi_period', 'koi_period_err1', 'koi_period_err2',
       'koi_time0bk', 'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact',
       'koi_impact_err1', 'koi_impact_err2', 'koi_duration',
       'koi_duration_err1', 'koi_duration_err2', 'koi_depth', 'koi_depth_err1',
       'koi_depth_err2', 'koi_prad', 'koi_prad_err1', 'koi_prad_err2',
       'koi_teq', 'koi_insol', 'koi_insol_err1', 'koi_insol_err2',
       'koi_model_snr', 'koi_tce_plnt_num', 'koi_steff', 'koi_steff_err1',
       'koi_steff_err2', 'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2',
       'koi_srad', 'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec',
       'koi_kepmag'],
      dtype='object')

# Select your features (columns)

In [43]:
list_features = columns[1:]
list_features

Index(['koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec',
       'koi_period', 'koi_period_err1', 'koi_period_err2', 'koi_time0bk',
       'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1',
       'koi_impact_err2', 'koi_duration', 'koi_duration_err1',
       'koi_duration_err2', 'koi_depth', 'koi_depth_err1', 'koi_depth_err2',
       'koi_prad', 'koi_prad_err1', 'koi_prad_err2', 'koi_teq', 'koi_insol',
       'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_steff', 'koi_steff_err1', 'koi_steff_err2', 'koi_slogg',
       'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad', 'koi_srad_err1',
       'koi_srad_err2', 'ra', 'dec', 'koi_kepmag'],
      dtype='object')

In [45]:
selected_features = df[list_features]
selected_features.head()

,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,-0.003520,...,-81,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,0,1,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,-0.000581,...,-176,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
2,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,-0.000115,...,-174,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
3,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,-0.001130,...,-211,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
4,0,0,0,0,4.134435,1.050000e-05,-1.050000e-05,172.979370,0.001900,-0.001900,...,-232,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714

# Create a Train Test Split

Use `koi_disposition` for the y values

In [46]:
X = selected_features
y = df["koi_disposition"]
print(X.shape, y.shape)

(6991, 40) (6991,)

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [48]:
X_train.head()

,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
4002,0,0,1,0,99.673478,3.463000e-04,-3.463000e-04,219.334830,0.002300,-0.002300,...,-148,4.777,0.040,-0.027,0.492,0.026,-0.027,293.05801,45.248821,15.801
4246,0,1,0,0,0.592244,9.000000e-08,-9.000000e-08,131.654831,0.000124,-0.000124,...,-146,4.664,0.056,-0.032,0.591,0.045,-0.045,290.28094,45.464260,15.653
548,0,1,1,0,9.991625,5.360000e-06,-5.360000e-06,137.447816,0.000445,-0.000445,...,-176,4.338,0.153,-0.187,1.096,0.309,-0.206,301.04239,45.022888,14.039
3953,0,1,0,0,178.412990,3.100000e-05,-3.100000e-05,218.225235,0.000127,-0.000127,...,-134,4.346,0.084,-0.126,1.148,0.202,-0.124,288.32785,38.627621,13.944
2362,0,0,0,0,45.294223,5.600000e-05,-5.600000e-05,138.678725,0.000987,-0.000987,...,-68,4.347,0.030,-0.030,1.044,0.057,-0.042,285.67938,50.241299,10.961

In [49]:
len(X_train)

5243

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [50]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [51]:
X_scaler = MinMaxScaler().fit(X_train)

In [52]:
# Transform the training and testing data using the X_scaler
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [53]:
# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [54]:
# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

# Train the Model

In [55]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [56]:
model = Sequential()
model.add(Dense(units=10, activation='relu', input_dim=40))
model.add(Dense(units=10, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

In [58]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Train on 5243 samples
Epoch 1/100
5243/5243 - 0s - loss: 0.2724 - acc: 0.8825
Epoch 2/100
5243/5243 - 0s - loss: 0.2747 - acc: 0.8795
Epoch 3/100
5243/5243 - 0s - loss: 0.2717 - acc: 0.8844
Epoch 4/100
5243/5243 - 0s - loss: 0.2721 - acc: 0.8817
Epoch 5/100
5243/5243 - 0s - loss: 0.2758 - acc: 0.8760
Epoch 6/100
5243/5243 - 0s - loss: 0.2726 - acc: 0.8793
Epoch 7/100
5243/5243 - 0s - loss: 0.2697 - acc: 0.8814
Epoch 8/100
5243/5243 - 0s - loss: 0.2695 - acc: 0.8823
Epoch 9/100
5243/5243 - 0s - loss: 0.2700 - acc: 0.8806
Epoch 10/100
5243/5243 - 0s - loss: 0.2717 - acc: 0.8814
Epoch 11/100
5243/5243 - 0s - loss: 0.2710 - acc: 0.8796
Epoch 12/100
5243/5243 - 0s - loss: 0.2707 - acc: 0.8806
Epoch 13/100
5243/5243 - 0s - loss: 0.2708 - acc: 0.8825
Epoch 14/100
5243/5243 - 0s - loss: 0.2687 - acc: 0.8816
Epoch 15/100
5243/5243 - 0s - loss: 0.2682 - acc: 0.8835
Epoch 16/100
5243/5243 - 0s - loss: 0.2668 - acc: 0.8859
Epoch 17/100
5243/5243 - 0s - loss: 0.2722 - acc: 0.8821
Epoch 18/100
5243/5243 - 0s - loss: 0.2676 - acc: 0.8840
Epoch 19/100
5243/5243 - 0s - loss: 0.2678 - acc: 0.8810
Epoch 20/100
5243/5243 - 0s - loss: 0.2665 - acc: 0.8821
Epoch 21/100
5243/5243 - 0s - loss: 0.2695 - acc: 0.8846
Epoch 22/100
5243/5243 - 0s - loss: 0.2709 - acc: 0.8831
Epoch 23/100
5243/5243 - 0s - loss: 0.2701 - acc: 0.8787
Epoch 24/100
5243/5243 - 0s - loss: 0.2678 - acc: 0.8802
Epoch 25/100
5243/5243 - 0s - loss: 0.2688 - acc: 0.8829
Epoch 26/100
5243/5243 - 0s - loss: 0.2680 - acc: 0.8825
Epoch 27/100
5243/5243 - 0s - loss: 0.2645 - acc: 0.8835
Epoch 28/100
5243/5243 - 0s - loss: 0.2641 - acc: 0.8879
Epoch 29/100
5243/5243 - 0s - loss: 0.2660 - acc: 0.8829
Epoch 30/100
5243/5243 - 0s - loss: 0.2645 - acc: 0.8856
Epoch 31/100
5243/5243 - 0s - loss: 0.2646 - acc: 0.8827
Epoch 32/100
5243/5243 - 0s - loss: 0.2658 - acc: 0.8823
Epoch 33/100
5243/5243 - 0s - loss: 0.2666 - acc: 0.8835
Epoch 34/100
5243/5243 - 0s - loss: 0.2643 - acc: 0.8831
Epoch 35/100
5243/5243 - 0s - loss: 0.2690 - acc: 0.8850
Epoch 36/100
5243/5243 - 0s - loss: 0.2627 - acc: 0.8846
Epoch 37/100
5243/5243 - 0s - loss: 0.2652 - acc: 0.8846
Epoch 38/100
5243/5243 - 0s - loss: 0.2643 - acc: 0.8859
Epoch 39/100
5243/5243 - 0s - loss: 0.2655 - acc: 0.8831
Epoch 40/100
5243/5243 - 0s - loss: 0.2623 - acc: 0.8877
Epoch 41/100
5243/5243 - 0s - loss: 0.2628 - acc: 0.8882
Epoch 42/100
5243/5243 - 0s - loss: 0.2639 - acc: 0.8865
Epoch 43/100
5243/5243 - 0s - loss: 0.2630 - acc: 0.8842
Epoch 44/100
5243/5243 - 0s - loss: 0.2617 - acc: 0.8896
Epoch 45/100
5243/5243 - 0s - loss: 0.2636 - acc: 0.8875
Epoch 46/100
5243/5243 - 0s - loss: 0.2675 - acc: 0.8806
Epoch 47/100
5243/5243 - 0s - loss: 0.2641 - acc: 0.8842
Epoch 48/100
5243/5243 - 0s - loss: 0.2626 - acc: 0.8846
Epoch 49/100
5243/5243 - 0s - loss: 0.2607 - acc: 0.8875
Epoch 50/100
5243/5243 - 0s - loss: 0.2596 - acc: 0.8880
Epoch 51/100
5243/5243 - 0s - loss: 0.2608 - acc: 0.8869
Epoch 52/100
5243/5243 - 0s - loss: 0.2619 - acc: 0.8852
Epoch 53/100
5243/5243 - 0s - loss: 0.2604 - acc: 0.8854
Epoch 54/100
5243/5243 - 0s - loss: 0.2602 - acc: 0.8901
Epoch 55/100
5243/5243 - 0s - loss: 0.2603 - acc: 0.8888
Epoch 56/100
5243/5243 - 0s - loss: 0.2580 - acc: 0.8869
Epoch 57/100
5243/5243 - 0s - loss: 0.2620 - acc: 0.8875
Epoch 58/100
5243/5243 - 0s - loss: 0.2594 - acc: 0.8890
Epoch 59/100
5243/5243 - 0s - loss: 0.2590 - acc: 0.8882
Epoch 60/100
5243/5243 - 0s - loss: 0.2574 - acc: 0.8911
Epoch 61/100
5243/5243 - 0s - loss: 0.2595 - acc: 0.8861
Epoch 62/100
5243/5243 - 0s - loss: 0.2591 - acc: 0.8880
Epoch 63/100
5243/5243 - 0s - loss: 0.2581 - acc: 0.8907
Epoch 64/100
5243/5243 - 0s - loss: 0.2584 - acc: 0.8932
Epoch 65/100
5243/5243 - 0s - loss: 0.2583 - acc: 0.8894
Epoch 66/100
5243/5243 - 0s - loss: 0.2576 - acc: 0.8905
Epoch 67/100
5243/5243 - 0s - loss: 0.2615 - acc: 0.8877
Epoch 68/100
5243/5243 - 0s - loss: 0.2584 - acc: 0.8886
Epoch 69/100
5243/5243 - 0s - loss: 0.2590 - acc: 0.8901
Epoch 70/100
5243/5243 - 0s - loss: 0.2620 - acc: 0.8848
Epoch 71/100
5243/5243 - 0s - loss: 0.2555 - acc: 0.8899
Epoch 72/100
5243/5243 - 0s - loss: 0.2564 - acc: 0.8905
Epoch 73/100
5243/5243 - 0s - loss: 0.2550 - acc: 0.8899
Epoch 74/100
5243/5243 - 0s - loss: 0.2564 - acc: 0.8901
Epoch 75/100
5243/5243 - 0s - loss: 0.2531 - acc: 0.8920
Epoch 76/100
5243/5243 - 0s - loss: 0.2571 - acc: 0.8926
Epoch 77/100
5243/5243 - 0s - loss: 0.2603 - acc: 0.8856
Epoch 78/100
5243/5243 - 0s - loss: 0.2555 - acc: 0.8896
Epoch 79/100
5243/5243 - 0s - loss: 0.2558 - acc: 0.8930
Epoch 80/100
5243/5243 - 0s - loss: 0.2541 - acc: 0.8913
Epoch 81/100
5243/5243 - 0s - loss: 0.2555 - acc: 0.8879
Epoch 82/100
5243/5243 - 0s - loss: 0.2573 - acc: 0.8898
Epoch 83/100
5243/5243 - 0s - loss: 0.2555 - acc: 0.8917
Epoch 84/100
5243/5243 - 0s - loss: 0.2532 - acc: 0.8913
Epoch 85/100
5243/5243 - 0s - loss: 0.2516 - acc: 0.8911
Epoch 86/100
5243/5243 - 0s - loss: 0.2537 - acc: 0.8928
Epoch 87/100
5243/5243 - 0s - loss: 0.2524 - acc: 0.8911
Epoch 88/100
5243/5243 - 0s - loss: 0.2535 - acc: 0.8919
Epoch 89/100
5243/5243 - 0s - loss: 0.2536 - acc: 0.8915
Epoch 90/100
5243/5243 - 0s - loss: 0.2538 - acc: 0.8896
Epoch 91/100
5243/5243 - 0s - loss: 0.2518 - acc: 0.8898
Epoch 92/100
5243/5243 - 0s - loss: 0.2529 - acc: 0.8913
Epoch 93/100
5243/5243 - 0s - loss: 0.2532 - acc: 0.8940
Epoch 94/100
5243/5243 - 0s - loss: 0.2568 - acc: 0.8896
Epoch 95/100
5243/5243 - 0s - loss: 0.2517 - acc: 0.8922
Epoch 96/100
5243/5243 - 0s - loss: 0.2504 - acc: 0.8919
Epoch 97/100
5243/5243 - 0s - loss: 0.2490 - acc: 0.8978
Epoch 98/100
5243/5243 - 0s - loss: 0.2492 - acc: 0.8905
Epoch 99/100
5243/5243 - 0s - loss: 0.2543 - acc: 0.8917
Epoch 100/100
5243/5243 - 0s - loss: 0.2505 - acc: 0.8940

# Evaluate and Predict

In [59]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

1748/1748 - 0s - loss: 0.2895 - acc: 0.8833
Normal Neural Network - Loss: 0.2895240332223731, Accuracy: 0.8832951784133911

In [60]:
predictions = model.predict_classes(X_test_scaled)

In [61]:
encoded_results = label_encoder.inverse_transform(predictions)

In [62]:
deepmodel_df = pd.DataFrame({"Prediction": encoded_results, "Actual": y_test})
deepmodel_df.reset_index(inplace=True, drop=True)
deepmodel_df

          Prediction          Actual
0          CANDIDATE       CANDIDATE
1     FALSE POSITIVE  FALSE POSITIVE
2     FALSE POSITIVE  FALSE POSITIVE
3          CANDIDATE       CANDIDATE
4     FALSE POSITIVE  FALSE POSITIVE
...              ...             ...
1743       CONFIRMED       CONFIRMED
1744  FALSE POSITIVE  FALSE POSITIVE
1745       CANDIDATE       CONFIRMED
1746       CONFIRMED       CONFIRMED
1747  FALSE POSITIVE  FALSE POSITIVE

[1748 rows x 2 columns]

# Save the Model

In [63]:
# dm_train_score=model.score(X_train_scaled, y_train_categorical)
# dm_test_score=model.score(X_test_scaled, y_test_categorical)
deepmodel_acc = pd.DataFrame({"model_loss": [model_loss], "model_accuracy": [model_accuracy]})
deepmodel_acc

   model_loss  model_accuracy
0    0.289524        0.883295

In [64]:
deepmodel_acc.to_csv("output/deepmodel_acc.csv")

In [65]:
model.save("DeepModel.h5")